### ISSUE TITLE
Search Result Component 만들기

### ISSUE THREAD

**Issue by NAPP4287** [codestates/Jurimma#12]
# ISSUE
- Group: `client`
- Type: `feature`
- Detail: create new component

# TODO
1. [x] Search Result Component 만들기
2. [x] 검색 여부 state 만들기
3. [x] 검색시 데이터 없을 때 표시되는 일러스트 만들기

# Estimated time
## `2h`
