### ISSUE TITLE
click event 구현

### ISSUE THREAD

**Issue by NAPP4287** [codestates/Jurimma#89]
# ISSUE
- Group:  `client`
- Type:  `event handling` 
- Detail: implementing click event

# TODO
1. [x] 로그인 click event
2. [x] modal창 닫기
3. [x] nav - edit profile button routing 하기
5. [x] login 상태 false일 때, 더보기 버튼 - login modal창 띄우기
6. [x] login 상태 true일 때, 새로 만들기 버튼 - modal창 띄우기
7. [x] login 상태 false일 때, 새로 만들기 버튼 - login modal창 띄우기

# Estimated time
